version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - default
  apm:
    image: docker.elastic.co/apm/apm-server:7.17.1
    ports:
      - 8200:8200
    environment:
      - output.elasticsearch.hosts=localhost:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    networks:
      - default
      - apm_connect
volumes:
  es_data:
networks:
  apm_connect:
    external: true